<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="2" time="0.007"><testcase classname="test_FK.FK" name="test_world_to_zero" time="0.0066" /><testcase classname="test_FK.FK" name="test_zero_to_one" time="0.0001"><error type="NameError">global name 'zero_to_one' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/marina/spot/src/tests/test_FK.py", line 32, in test_zero_to_one
    output = zero_to_one(A, length, width)
</error></testcase><system-out>&lt;![CDATA[
done test for world - zero frames

]]&gt;</system-out><system-err>&lt;![CDATA[
/usr/lib/python2.7/unittest/case.py:519: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if not first != second:

]]&gt;</system-err></testsuite>